iio: hmc425a: limit GPIOs to 6 (max)
There build warnings/errors in the newer kernel is:
```
drivers/iio/amplifiers/hmc425a.c:50:2: error: ISO C90 forbids variable length array 'values' [-Werror=vla]
   50 |  int i, values[st->gpios->ndescs];
      |  ^~~
```

Seems that it does not allow C99 variable-length-arrays.
This change also enforces a max of 6 GPIOs via DT [which is what the device
supports], and limits only the use of the first 6 [if more are specified]
while printing a warning.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>